#!/bin/bash


#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:30:00
#SBATCH --mem=16GB
#SBATCH --gres=gpu:mi250:1
#SBATCH --job-name=find_diffeo
#SBATCH --output=slurm_%j.out
#SBATCH --error=slurm_%j.err


module purge


singularity exec \
  --overlay /vast/xj2173/singularity_envir/diffeo-amd-env.ext3:ro \
  --overlay /vast/work/public/ml-datasets/imagenet/imagenet-val.sqf:ro      \
  --overlay /vast/work/public/ml-datasets/imagenet/imagenet-test.sqf:ro     \
  --overlay /vast/work/public/ml-datasets/imagenet/imagenet-train.sqf:ro    \
  /scratch/work/public/singularity/rocm6.2-ubuntu22.04.5.sif \
  /bin/bash -c "source /ext3/env.sh; \
  python /vast/xj2173/diffeo/sbatch_model_invar_eval.py"