#!/bin/bash


#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=1
#SBATCH --time=00:30:00
#SBATCH --mem=16GB
#SBATCH --gres=gpu:h100:1
#SBATCH --job-name=find_diffeo
#SBATCH --output=slurm_%j.out
#SBATCH --error=slurm_%j.err


module purge


singularity exec --nv \
  --overlay /vast/xj2173/singularity_envir/diffeo-env.ext3:ro \
  --overlay /vast/work/public/ml-datasets/imagenet/imagenet-val.sqf:ro      \
  --overlay /vast/work/public/ml-datasets/imagenet/imagenet-test.sqf:ro     \
  --overlay /vast/work/public/ml-datasets/imagenet/imagenet-train.sqf:ro    \
  /scratch/work/public/singularity/cuda12.1.1-cudnn8.9.0-devel-ubuntu22.04.2.sif \
  /bin/bash -c "source /ext3/env.sh; python /vast/xj2173/diffeo/sbatch_find_save_inv_diffeo.py"